# coding: utf-8

"""
    GLACIATION Metadata Service

    The service exposes API to work with Distributed Knowledge Graph

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from template_web_client.api.monitoring_api import MonitoringApi


class TestMonitoringApi(unittest.TestCase):
    """MonitoringApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MonitoringApi()

    def tearDown(self) -> None:
        pass

    def test_metrics_metrics_get(self) -> None:
        """Test case for metrics_metrics_get

        Metrics
        """
        pass


if __name__ == '__main__':
    unittest.main()
