# coding: utf-8

"""
    GLACIATION Metadata Service

    The service exposes API to work with Distributed Knowledge Graph

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from template_web_client.api.graph_api import GraphApi


class TestGraphApi(unittest.TestCase):
    """GraphApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GraphApi()

    def tearDown(self) -> None:
        pass

    def test_update_graph_api_v0_graph_patch(self) -> None:
        """Test case for update_graph_api_v0_graph_patch

        Update Graph
        """
        pass


if __name__ == '__main__':
    unittest.main()
